[project]
name = "csv2table"
version = "0.1.0"
description = "Easily convert your csv files into beautiful tables"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "great-tables>=0.14.0",
    "polars>=1.14.0",
]
